"""Build and size-check QASPER passage corpora from verified paper exports."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from src.data.chunking import (
    ChunkingConfig,
    build_passages_from_record,
    validate_built_passages,
)
from src.data.passage_ids import PassageIdContext
from src.data.qasper_export import SPLITS, load_verified_papers
from src.data.split_policy import OFFICIAL_TO_PROJECT_ROLE

MIN_PASSAGES = 10_000
MIN_WORDS = 100_000
SCOPES = ("development", "all-paper-text")
SCOPE_SPLITS = {
    "development": ("train", "validation"),
    "all-paper-text": SPLITS,
}


def _source_words(record: dict[str, Any], built: tuple[Any, ...]) -> int:
    """Count source words once, excluding chunks' repeated overlap text."""

    indices: dict[int, set[int]] = defaultdict(set)
    for item in built:
        indices[item.coordinate.section_index].update(item.paragraph_indices)
    count = 0
    for section_index, paragraph_indices in indices.items():
        paragraphs = record["full_text"][section_index]["paragraphs"]
        count += sum(len(paragraphs[index].strip().split()) for index in paragraph_indices)
    return count


def _corpus_bytes(passages: list[Any]) -> bytes:
    lines = (
        json.dumps(
            item.passage.model_dump(mode="json"),
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        for item in passages
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def _publish(output: Path, manifest_output: Path, corpus_bytes: bytes, manifest_bytes: bytes) -> None:
    targets = (output, manifest_output)
    if len({path.resolve(strict=False) for path in targets}) != 2:
        raise ValueError("corpus and manifest output paths must differ")
    if any(path.exists() or path.is_symlink() for path in targets):
        raise FileExistsError("corpus or manifest output already exists")
    temporary_paths = (
        output.with_name(f"tmp_{output.name}"),
        manifest_output.with_name(f"tmp_{manifest_output.name}"),
    )
    if any(path.exists() or path.is_symlink() for path in temporary_paths):
        raise FileExistsError("temporary corpus or manifest output already exists")
    output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    try:
        for path, content in zip(temporary_paths, (corpus_bytes, manifest_bytes), strict=True):
            with path.open("xb") as handle:
                created.append(path)
                handle.write(content)
        if temporary_paths[0].read_bytes() != corpus_bytes:
            raise OSError("staged corpus bytes differ from generated bytes")
        if temporary_paths[1].read_bytes() != manifest_bytes:
            raise OSError("staged manifest bytes differ from generated bytes")
        os.replace(temporary_paths[0], output)
        created.remove(temporary_paths[0])
        os.replace(temporary_paths[1], manifest_output)
        created.remove(temporary_paths[1])
    except Exception:
        for path in created:
            try:
                path.unlink(missing_ok=True)
            except OSError:
                pass
        raise


def build_corpus(
    *,
    papers: Path,
    export_manifest: Path,
    output: Path,
    manifest_output: Path,
    scope: str = "development",
    chunk_size_words: int = 200,
    chunk_overlap_words: int = 40,
) -> dict[str, Any]:
    """Build passages from the selected scope of a verified paper-only export."""

    if scope not in SCOPES:
        raise ValueError(f"scope must be one of {SCOPES!r}")
    output = Path(output)
    manifest_output = Path(manifest_output)
    if any(path.exists() or path.is_symlink() for path in (output, manifest_output)):
        raise FileExistsError("corpus or manifest output already exists")

    export, paper_records = load_verified_papers(
        papers_path=Path(papers), manifest_path=Path(export_manifest)
    )
    source = export["source"]
    config = ChunkingConfig(
        chunk_size_words=chunk_size_words,
        chunk_overlap_words=chunk_overlap_words,
    )
    context = PassageIdContext(
        dataset_id=source["dataset_id"],
        resolved_revision=source["resolved_revision"],
        local_parser_version=source["local_parser_version"],
        normalization_version=config.normalization_version,
        chunking_version=config.chunking_version,
        chunk_size_words=config.chunk_size_words,
        chunk_overlap_words=config.chunk_overlap_words,
    )
    selected_splits = set(SCOPE_SPLITS[scope])
    passages: list[Any] = []
    source_word_count = 0
    split_counts: dict[str, dict[str, int | str | bool]] = {
        split: {
            "project_role": OFFICIAL_TO_PROJECT_ROLE[split],
            "included_in_scope": split in selected_splits,
            "source_paper_count": export["split_counts"][split]["papers"],
            "passage_count": 0,
        }
        for split in SPLITS
    }
    for record in paper_records:
        split = record["source_split"]
        if split not in selected_splits:
            continue
        result = build_passages_from_record(record, context=context, config=config)
        split_counts[split]["passage_count"] += len(result.passages)
        source_word_count += _source_words(record, result.passages)
        passages.extend(result.passages)

    validate_built_passages(passages)
    passage_word_count = sum(len(item.passage.text.split()) for item in passages)
    if len(passages) < MIN_PASSAGES or source_word_count < MIN_WORDS:
        raise ValueError(
            f"corpus below rubric minimum: {len(passages)} passages, "
            f"{source_word_count} source words; require {MIN_PASSAGES} and {MIN_WORDS}"
        )
    if passage_word_count < MIN_WORDS:
        raise ValueError("chunked passage word count is below rubric minimum")
    word_types = {
        token.casefold()
        for item in passages
        for token in item.passage.text.split()
    }
    corpus_bytes = _corpus_bytes(passages)
    corpus_sha256 = hashlib.sha256(corpus_bytes).hexdigest()
    purpose = "index_for_inference" if scope == "all-paper-text" else "development"
    artifact = "inference_corpus" if scope == "all-paper-text" else "development_corpus"
    included_paper_count = sum(
        counts["source_paper_count"]
        for split, counts in split_counts.items()
        if split in selected_splits
    )
    manifest: dict[str, Any] = {
        "manifest_schema_version": 1,
        "artifact": artifact,
        "purpose": purpose,
        "scope": scope,
        "source": {
            "dataset_id": source["dataset_id"],
            "resolved_revision": source["resolved_revision"],
            "local_parser_version": source["local_parser_version"],
            "export_papers_file": export["outputs"]["papers"]["file"],
            "export_papers_sha256": export["outputs"]["papers"]["sha256"],
            "source_splits": source["split_files"],
            "split_policy_version": export["split_policy_version"],
            "split_counts": split_counts,
        },
        "chunking": {
            "source_kinds": ["full_text"],
            "normalization_version": config.normalization_version,
            "chunking_version": config.chunking_version,
            "chunk_size_words": config.chunk_size_words,
            "chunk_overlap_words": config.chunk_overlap_words,
            "word_rule": "Unicode-aware non-whitespace runs (str.split)",
            "type_rule": "casefolded non-whitespace runs from passage text",
        },
        "output": {
            "file": output.name,
            "sha256": corpus_sha256,
            "scope": scope,
            "purpose": purpose,
            "source_paper_count": included_paper_count,
            "indexed_paper_count": len({item.passage.paper_id for item in passages}),
            "passage_count": len(passages),
            "unique_passage_count": len({item.passage.passage_id for item in passages}),
            "source_word_count": source_word_count,
            "passage_word_count": passage_word_count,
            "passage_word_type_count": len(word_types),
            "minimum_passages": MIN_PASSAGES,
            "minimum_words": MIN_WORDS,
            "rubric_minimum_met": True,
        },
    }
    manifest_bytes = (
        json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False)
        + "\n"
    ).encode("utf-8")
    _publish(output, manifest_output, corpus_bytes, manifest_bytes)
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--papers", type=Path, required=True)
    parser.add_argument("--export-manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--manifest-output", type=Path, required=True)
    parser.add_argument("--scope", choices=SCOPES, default="development")
    parser.add_argument("--chunk-size-words", type=int, default=200)
    parser.add_argument("--chunk-overlap-words", type=int, default=40)
    args = parser.parse_args()
    try:
        manifest = build_corpus(**vars(args))
    except (FileExistsError, OSError, ValueError, TypeError, KeyError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(json.dumps(manifest["output"], sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
